export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const EDIT_USER_BEGIN = 'EDIT_USER_BEGIN'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR'

export const LOG_OUT_USER = 'LOG_OUT_USER'



export const CREATE_NOTE_BEGIN = "CREATE_NOTE_BEGIN";
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
export const CREATE_NOTE_ERROR = "CREATE_NOTE_ERROR";

export const GET_NOTES_BEGIN = 'GET_NOTES_BEGIN'
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS'
export const GET_NOTES_ERROR = 'GET_NOTES_ERROR'

export const DELETE_NOTE_BEGIN = 'DELETE_NOTE_BEGIN'
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS'
export const DELETE_NOTE_ERROR = 'DELETE_NOTE_ERROR'


export const EDIT_NOTE_BEGIN = 'EDIT_NOTE_BEGIN'
export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS'
export const EDIT_NOTE_ERROR = 'EDIT_NOTE_ERROR'



export const TOGGLE_EDIT_STATE = 'TOGGLE_EDIT_STATE'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const HANDLE_DARK_MODE = 'HANDLE_DARK_MODE'